apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 99999.dkr.ecr.us-east-2.amazonaws.com/mlzoomcamp-images:zoomcamp-10-gateway-001
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9696
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: TF_SERVING_HOST
              value: tf-serving-clothing-model.default.svc.cluster.local:8500
      restartPolicy: Always
      
