-- Script: cleaning_xcoms.sql
-- Purpose: Clean up old or unnecessary XCom records from the Airflow metadata database.
-- WARNING: Ensure you take a backup of your database before executing this script.

-- Define the retention period (e.g., delete XComs older than 30 days)
-- Script: cleaning_xcoms.sql
-- Purpose: Delete XComs generated by the specified DAG.

DELETE FROM xcom
WHERE dag_id = '34_xcoms_dag';


-- Optionally, clean specific XComs by key (if needed)
-- DELETE FROM xcom
-- WHERE key = 'specific_key_to_remove';

-- Optionally, clean XComs for specific DAGs or task_ids
-- DELETE FROM xcom
-- WHERE dag_id = 'example_dag'
--   AND task_id = 'example_task';
